# Generated by Django 3.2.3 on 2021-05-26 09:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description_short', tinymce.models.HTMLField()),
                ('description_long', tinymce.models.HTMLField()),
                ('latitude', models.CharField(blank=True, max_length=25)),
                ('longitude', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('number', models.PositiveIntegerField(default=0)),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='places.place')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
