# Generated by Django 2.2.7 on 2021-08-03 09:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', tinymce.models.HTMLField(blank=True)),
                ('description_long', tinymce.models.HTMLField(blank=True)),
                ('latitude', models.FloatField(blank=True, max_length=25)),
                ('longitude', models.FloatField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
