# Generated by Django 2.2.7 on 2021-08-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210803_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('number',), 'verbose_name': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Места'},
        ),
    ]
