# Generated by Django 2.2.7 on 2021-08-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210803_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('number',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
