# Generated by Django 3.2.3 on 2021-05-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place'),
        ),
    ]
