# Generated by Django 3.2.3 on 2021-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
