# Generated by Django 3.2.3 on 2021-05-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20210526_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='places',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place'),
        ),
    ]
